# Generated by Django 2.0.2 on 2018-02-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Appmodel',
        ),
    ]
